[general]
import = ["theme.toml"]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
startup_mode = "Windowed"
decorations = "None"
opacity = 0.8

[window.padding]
x = 25 
y = 25 

[font]
size = 11

[font.offset]
x = 0
y = 0

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"

[font.italic]
family = "Hurmit Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hurmit Nerd Font"
style = "Bold Italic"

[cursor.style]
shape = "Underline"
blinking = "Always"

[selection]
save_to_clipboard = true
