[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"

[colors.cursor]
cursor = "#F5E0DC"
text   = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text       = "#1E1E2E"

[colors.normal]
black   = "#43465A"   
red     = "#F38BA8"   
green   = "#A6E3A1"   
yellow  = "#F9E2AF"   
blue    = "#87B0F9"   
magenta = "#F5C2E7"   
cyan    = "#94E2D5"   
white   = "#CDD6F4"   

[colors.bright]
black   = "#43465A"   
red     = "#F38BA8"
green   = "#A6E3A1"   
yellow  = "#F9E2AF" 
blue    = "#87B0F9"   
magenta = "#F5C2E7" 
cyan    = "#94E2D5"
white   = "#A1A8C9"

